telegram:
  bot_token: "YOUR_BOT_TOKEN"
  allowed_users:
    - "YOUR_CHAT_ID"
  bonkbot_chat_id: "BONKBOT_CHAT_ID"

apis:
  dexscreener: "https://api.dexscreener.com/latest/dex"
  rugcheck: "YOUR_RUGCHECK_API_KEY"

trading:
  default_size: 0.1  # ETH
  max_slippage: 1.5  # %
  
filters:
  bundled_supply_threshold: 40